### ISSUE TITLE
canonicalizeResource Object.keys() breaks in node 0.11

### ISSUE THREAD

**Issue by tmarshall** [LearnBoost/knox#249]
My tests are working when using v0.10, but break in v0.11

```
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Object.exports.canonicalizeResource (/Users/mars/dev/node_modules/knox/lib/auth.js:210:10)
    at Client.request (/Users/mars/dev/node_modules/knox/lib/client.js:275:22)
    at Client.put (/Users/mars/dev/node_modules/knox/lib/client.js:326:15)
    at Client.putStream (/Users/mars/dev/node_modules/knox/lib/client.js:408:18)
    at /Users/mars/dev/api/v0/nodes/account.js:269:18
    at /Users/mars/dev/node_modules/async/lib/async.js:570:21
    at /Users/mars/dev/node_modules/async/lib/async.js:249:17
    at /Users/mars/dev/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
```

I logged `url` in `/lib/auth.js`'s `canonicalizeResource()`

0.10:
```js
{ protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: '',
  query: {},
  pathname: '/dev/ifL1T/-JY6tjvunPCwVBdifL1T.png',
  path: '/dev/ifL1T/-JY6tjvunPCwVBdifL1T.png',
  href: '/dev/ifL1T/-JY6tjvunPCwVBdifL1T.png' }
```

0.11:
```js
{ protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: null,
  pathname: '/dev/ifL1T/-JY6tjvunPCwVBdifL1T.png',
  path: '/dev/ifL1T/-JY6tjvunPCwVBdifL1T.png',
  href: '/dev/ifL1T/-JY6tjvunPCwVBdifL1T.png' }
```

`Object.keys(url.query)` expects `{}` at minimum

**Comment by ELLIOTTCABLE** [comment]
Do you have a reference to the bug on Node itself? I'm seeing similar behaviour elsewhere.
